default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'root' }%>
  password: <%= ENV.fetch('MYSQL_PASSWORD') {'password'}%>
  host: <%= ENV.fetch('MYSQL_HOST') %>
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: fit_care_health_development

test:
  <<: *default
  database: fit_care_health_test

production:
  <<: *default
  database: fit_care_health_production
  username: fit_care_health
  password: password